<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIiV9yYH\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIiV9yYH/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerIiV9yYH.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerIiV9yYH\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerIiV9yYH\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'IiV9yYH',
    'container.build_id' => 'c54fe129',
    'container.build_time' => 1524052499,
));
