<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVpZ8z8w\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVpZ8z8w/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerVpZ8z8w.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerVpZ8z8w\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerVpZ8z8w\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'VpZ8z8w',
    'container.build_id' => 'ececf970',
    'container.build_time' => 1523950750,
));
